//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoGameWindowsStarter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonoGameWindowsStarter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 2
        ///6 7
        ///10 10
        ///1 12
        ///14 12
        ///.
        /// </summary>
        internal static string Level1SpikePlacements {
            get {
                return ResourceManager.GetString("Level1SpikePlacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0 
        ///1 0
        ///2 0
        ///3 0
        ///4 0
        ///5 0
        ///6 0
        ///7 0
        ///8 0
        ///9 0
        ///10 0
        ///11 0
        ///12 0
        ///13 0
        ///14 0
        ///15 0
        ///16 0
        ///17 0
        ///18 0
        ///19 0
        ///20 0 
        ///0 1 
        ///13 1
        ///14 1
        ///18 1
        ///20 1
        ///0 2
        ///2 2
        ///3 2
        ///4 2
        ///5 2
        ///6 2
        ///7 2
        ///8 2
        ///9 2
        ///10 2
        ///11 2
        ///16 2
        ///20 2
        ///0 3
        ///9 3
        ///11 3
        ///12 3
        ///13 3
        ///14 3
        ///16 3
        ///17 3
        ///19 3
        ///20 3
        ///0 4
        ///1 4
        ///2 4
        ///3 4
        ///4 4
        ///5 4
        ///6 4
        ///7 4
        ///12 4
        ///17 4
        ///20 4
        ///0 5
        ///7 5
        ///9 5
        ///10 5
        ///12 5
        ///14 5
        ///16 5
        ///17 5
        ///18 5
        ///20 5
        ///0 6
        ///1 6
        ///2 6
        ///3 6
        ///4 6
        ///5 6
        ///7 6
        ///10 6 
        ///13 6
        ///14 6
        ///15 6
        ///16 6
        ///18 6
        ///20 6
        ///8 7
        ///10 7
        ///11 7
        ///12 7
        ///14 7
        ///18 7
        ///0 8
        ///1 8        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1WallPlacements {
            get {
                return ResourceManager.GetString("Level1WallPlacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 3
        ///1 6
        ///1 8
        ///17 9
        ///19 12
        ///.
        /// </summary>
        internal static string Level2SpikePlacements {
            get {
                return ResourceManager.GetString("Level2SpikePlacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0
        ///1 0	
        ///2 0	
        ///3 0	
        ///4 0	
        ///5 0	
        ///6 0	
        ///7 0	
        ///8 0	
        ///9 0	
        ///10 0	
        ///11 0	
        ///12 0	
        ///13 0	
        ///14 0	
        ///15 0	
        ///16 0	
        ///17 0	
        ///18 0	
        ///19 0	
        ///20 0
        ///0 1																				
        ///20 1
        ///0 2		
        ///2 2	
        ///3 2	
        ///4 2	
        ///5 2	
        ///6 2	
        ///7 2	
        ///8 2	
        ///9 2	
        ///10 2	
        ///11 2	
        ///12 2	
        ///13 2	
        ///14 2		
        ///16 2	
        ///17 2	
        ///18 2		
        ///20 2
        ///0 3														
        ///14 3		
        ///16 3		
        ///18 3		
        ///20 3
        ///0 4
        ///2 4
        ///3 4
        ///4 4
        ///5 4
        ///6 4
        ///7 4
        ///8 4
        ///9 4
        ///10 4
        ///11 4
        ///12 4
        ///14 4
        ///16 4
        ///18 4
        ///20 4
        ///0 5
        ///12 5
        ///14 5
        ///16 5
        ///18 5
        ///19 5
        ///20 5
        ///0 6
        ///2 6
        ///3 6
        ///4 6
        ///5 6
        ///6 6
        ///7 6
        ///8 6
        ///9 6
        ///10 6
        ///12 6
        ///14 6
        ///16 6
        ///20 6
        ///2 7
        ///12 7
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2WallPlacements {
            get {
                return ResourceManager.GetString("Level2WallPlacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 2
        ///8 4
        ///3 5
        ///8 5
        ///8 6
        ///8 7
        ///8 8
        ///12 8
        ///8 9
        ///1 10
        ///14 12
        ///3 13
        ///19 14.
        /// </summary>
        internal static string Level3SpikePlacements {
            get {
                return ResourceManager.GetString("Level3SpikePlacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0
        ///0 1
        ///0 2
        ///0 3
        ///0 4
        ///0 5
        ///0 6
        ///0 7
        ///0 8
        ///0 9
        ///0 10
        ///0 11
        ///0 12
        ///0 14
        ///0 15
        ///1 0
        ///1 12
        ///1 14
        ///1 15
        ///2 0
        ///2 2
        ///2 3
        ///2 4
        ///2 5
        ///2 6
        ///2 7
        ///2 8
        ///2 9
        ///2 10
        ///2 11
        ///2 12
        ///2 15
        ///3 0
        ///3 15
        ///4 0
        ///4 2
        ///4 3
        ///4 4
        ///4 5
        ///4 6
        ///4 7
        ///4 8
        ///4 9
        ///4 10
        ///4 11
        ///4 12
        ///4 13
        ///4 15
        ///5 0
        ///5 2
        ///5 15
        ///6 0
        ///6 2
        ///6 4
        ///6 5
        ///6 7
        ///6 8
        ///6 9
        ///6 11
        ///6 12
        ///6 13
        ///6 14
        ///6 15
        ///7 0
        ///7 2
        ///7 4
        ///7 6
        ///7 7
        ///7 9
        ///7 10
        ///7 11
        ///7 15
        ///8 0
        ///8 2
        ///8 13
        ///8 15
        ///9 0
        ///9 2
        ///9 3
        ///9 4
        ///9 5
        ///9 6
        ///9 7
        ///9 8
        ///9 9
        ///9 10
        ///9 11
        ///9 13
        ///9 15
        ///10 0
        ///10 2
        ///10 13
        ///10 15
        ///11 0
        ///11 2
        ///11 4
        ///11 5
        ///11 6
        ///11  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3WallPlacements {
            get {
                return ResourceManager.GetString("Level3WallPlacements", resourceCulture);
            }
        }
    }
}
